export const COLLECTION_ADMINS = "admins"
export const COLLECTION_LECTURERS = "lecturers"
export const COLLECTION_COURSES = "courses"
export const HOD = "hod"
export const LECTURER = "lecturer"
export const EXPIRED = "expired"
export const FIRST_SEMESTER = "first"
export const SECOND_SEMESTER = "second"